const BASE_API_ENDPOINT = 'http://127.0.0.1:8000/api/';

const GET_ALL_PRODUCTS_ENDPOINT = 'products';
const GET_SINGLE_PRODUCT_ENDPOINT = 'products/';

export {
  BASE_API_ENDPOINT,
  GET_ALL_PRODUCTS_ENDPOINT,
  GET_SINGLE_PRODUCT_ENDPOINT
};
