const BASE_API_ENDPOINT = 'http://127.0.0.1:8000/api/';

const USER_LOG_IN_ENDPOINT = 'user/login';
const USER_LOG_OUT_ENDPOINT = 'user/logout';
const USER_REGISTER_ENDPOINT = 'user/register';
const USER_GET_INFO_ENDPOINT = 'user/me';

const GET_ALL_PRODUCTS_ENDPOINT = 'products';
const GET_SINGLE_PRODUCT_ENDPOINT = 'products/';

export {
  BASE_API_ENDPOINT,
  GET_ALL_PRODUCTS_ENDPOINT,
  GET_SINGLE_PRODUCT_ENDPOINT,
  USER_LOG_IN_ENDPOINT,
  USER_LOG_OUT_ENDPOINT,
  USER_REGISTER_ENDPOINT,
  USER_GET_INFO_ENDPOINT
};
