const BASE_API_ENDPOINT = 'http://127.0.0.1:8000/api/';

const USER_LOG_IN_ENDPOINT = 'user/login';
const USER_LOG_OUT_ENDPOINT = 'user/logout';
const USER_REGISTER_ENDPOINT = 'user/register';
const USER_GET_INFO_ENDPOINT = 'user/me';
const USER_CREATE_ORDER_ENDPOINT = 'user/createOrder';
const USER_GET_ALL_ORDERS_ENDPOINT = 'user/orders';
const USER_GET_DETAIL_ORDER_ENDPOINT = 'user/orders/';

const ADMIN_LOG_IN_ENDPOINT = 'admin/login';
const ADMIN_GET_INFO_ENDPOINT = 'admin/me';
const ADMIN_LOG_OUT_ENDPOINT = 'admin/logout';
const ADMIN_GET_ALL_ORDERS_ENDPOINT = 'admin/orders';
const ADMIN_GET_DETAIL_ORDER_ENDPOINT = 'admin/orders/';

const GET_ALL_PRODUCTS_ENDPOINT = 'products';
const GET_SINGLE_PRODUCT_ENDPOINT = 'products/';

export {
  BASE_API_ENDPOINT,
  GET_ALL_PRODUCTS_ENDPOINT,
  GET_SINGLE_PRODUCT_ENDPOINT,
  USER_LOG_IN_ENDPOINT,
  USER_LOG_OUT_ENDPOINT,
  USER_REGISTER_ENDPOINT,
  USER_GET_INFO_ENDPOINT,
  USER_CREATE_ORDER_ENDPOINT,
  USER_GET_ALL_ORDERS_ENDPOINT,
  USER_GET_DETAIL_ORDER_ENDPOINT,
  ADMIN_LOG_IN_ENDPOINT,
  ADMIN_GET_INFO_ENDPOINT,
  ADMIN_LOG_OUT_ENDPOINT,
  ADMIN_GET_ALL_ORDERS_ENDPOINT,
  ADMIN_GET_DETAIL_ORDER_ENDPOINT
};
